name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          # Conectar via SSH e executar comandos de deploy
          ssh $VPS_USER@$VPS_HOST << 'EOL'
            # Navegar até o diretório da aplicação
            cd /var/www/tabata

            # Backup do .env se existir
            if [ -f .env ]; then
              cp .env .env.backup
            fi

            # Atualizar código
            git fetch origin main
            git reset --hard origin/main

            # Restaurar .env
            if [ -f .env.backup ]; then
              mv .env.backup .env
            fi

            # Instalar dependências e fazer build
            npm install
            npm run build

            # Reiniciar a aplicação
            pm2 delete tabata 2>/dev/null || true
            pm2 start npm --name "tabata" -- start
            pm2 save
          EOL
